package com.lzh.administrator.androidframe.GreenDAo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lzh.administrator.androidframe.GreenDAo.StationBean;

import com.lzh.administrator.androidframe.GreenDAo.StationBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stationBeanDaoConfig;

    private final StationBeanDao stationBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stationBeanDaoConfig = daoConfigMap.get(StationBeanDao.class).clone();
        stationBeanDaoConfig.initIdentityScope(type);

        stationBeanDao = new StationBeanDao(stationBeanDaoConfig, this);

        registerDao(StationBean.class, stationBeanDao);
    }
    
    public void clear() {
        stationBeanDaoConfig.getIdentityScope().clear();
    }

    public StationBeanDao getStationBeanDao() {
        return stationBeanDao;
    }

}
