package com.lzh.administrator.androidframe.GreenDAo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STATION_BEAN".
 */
public class StationBean {

    private Long id;
    private String name;
    private String pinyin;
    private String pinyins;
    private String stationcode;
    private String firstpys;

    public StationBean() {
    }

    public StationBean(Long id) {
        this.id = id;
    }

    public StationBean(Long id, String name, String pinyin, String pinyins, String stationcode, String firstpys) {
        this.id = id;
        this.name = name;
        this.pinyin = pinyin;
        this.pinyins = pinyins;
        this.stationcode = stationcode;
        this.firstpys = firstpys;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    public String getPinyins() {
        return pinyins;
    }

    public void setPinyins(String pinyins) {
        this.pinyins = pinyins;
    }

    public String getStationcode() {
        return stationcode;
    }

    public void setStationcode(String stationcode) {
        this.stationcode = stationcode;
    }

    public String getFirstpys() {
        return firstpys;
    }

    public void setFirstpys(String firstpys) {
        this.firstpys = firstpys;
    }

}
